### ISSUE TITLE
Having trouble constructing boundary patches for external use

### ISSUE THREAD

**Issue by VadiMysore** [PixarAnimationStudios/OpenSubdiv#1150]
Hi there!
In order to accurately represent the infinitely sharp edges in a SubD model, I am using the useInfSharpPatch option with Far::PatchTableFactory::Create.

The patches at the sharp crease are like boundary patches and some of their control vertices need to be extrapolated like we do with the boundary patches. 

@barfowl suggested the following extrapolation scheme for boundary patches.

//  Don't extrapolate corner points until all boundary points in place
    if ((boundaryMask & 1) != 0) {
        cpt[1] = 2*cpt[5] - cpt[9];
        cpt[2] = 2*cpt[6] - cpt[10];
    }
    if ((boundaryMask & 2) != 0) {
        cpt[7] = 2*cpt[6] - cpt[5];
        cpt[11] = 2*cpt[10] - cpt[9];
    }
    if ((boundaryMask & 4) != 0) {
        cpt[13] = 2*cpt[9] - cpt[5];
        cpt[14] = 2*cpt[10] - cpt[6];
    }
    if ((boundaryMask & 8) != 0) {
        cpt[4] = 2*cpt[5] - cpt[6];
        cpt[8] = 2*cpt[9] - cpt[10];
    }

    //  Now safe to extrapolate corner points:
    if ((boundaryMask & 1) != 0) {
        cpt[0] = 2*cpt[4] - cpt[8];
        cpt[3] = 2*cpt[7] - cpt[11];
    }
    if ((boundaryMask & 2) != 0) {
        cpt[3] = 2*cpt[2] - cpt[1];
        cpt[15] = 2*cpt[14] - cpt[13];
    }
    if ((boundaryMask & 4) != 0) {
        cpt[12] = 2*cpt[8] - cpt[4];
        cpt[15] = 2*cpt[11] - cpt[7];
    }
    if ((boundaryMask & 8) != 0) {
        cpt[0] = 2*cpt[1] - cpt[2];
        cpt[12] = 2*cpt[13] - cpt[14];
    }
The above logic works great and seems to produce correct boundary patches. But for infinitely sharp edges that have have faces on either side, then the boundary patches do not seem to meet at the corners as shown below for a simple case.

![InfinitelySharpEdgesIssue](https://user-images.githubusercontent.com/24560022/60606316-bcc65500-9d80-11e9-82f4-ebbebe40d8e3.jpg)

Is the problem with the above extrapolation scheme?

**Comment by barfowl** [comment]
The extrapolation scheme should be fine.  It is standard linear extrapolation of phantom cubic B-Spline points and is nothing special.  It has been working effectively for both boundary patches since 3.0 (possibly earlier) and inf-sharp patches since 3.1.

Here is your simple example with inf-sharp patches correctly generated and tessellated in the glViewer example:

![inf_sharp_quads](https://user-images.githubusercontent.com/4130807/60619848-69f39a00-9d8e-11e9-812b-2cc215edbb43.png)

Several other examples illustrate crack free patches along interior inf-sharp edges.

The extrapolation code here is completely independent of the "inf-sharp patch" context -- all it takes as input is a mask indicating which edges are boundaries.  So if your code is working for patches along boundaries but not interior inf-sharp edges, I would suspect something else as the cause.

**Comment by VadiMysore** [comment]
@barfowl - Hi Barry! Thanks for the response.

Even my code is independent totally of the "inf-sharp patch" context. Below is my code that is based on your earlier suggestion, which is used both for the real boundary patches and for patches bordering infinitely sharp edges as in this case. I do not do anything special for the "inf-sharp patch" context. I have checked and rechecked the code below. I do not find any issues.

//Handle the boundary patches, if any.
for (int i = 0; i < (int) boundaryPatches.size(); i++)
{ 
              unsigned short boundaryStatus = 0;
	      Far::ConstIndexArray controlVertexIndices;
	      IntSet extrapolatedCVIndices;
	     SESubdivVertex patchControlVerticesArray[16];

             Far::PatchParam patchParam = patchTable->GetPatchParam(array, boundaryPatches[i]);

	     boundaryStatus = patchParam.GetBoundary();

	    controlVertexIndices = patchTable->GetPatchVertices(array, boundaryPatches[i]);

            //  Don't extrapolate corner points until all boundary points in place
	    if ((boundaryStatus & 1) != 0)
	   {
		patchControlVerticesArray[1] = (allSUbdivVertices[controlVertexIndices[5]] * 2) - 
                                                                    allSUbdivVertices[controlVertexIndices[9]];
		patchControlVerticesArray[2] = (allSUbdivVertices[controlVertexIndices[6]] * 2) - 
                                                                    allSUbdivVertices[controlVertexIndices[10]];

		extrapolatedCVIndices.insert(1);
		extrapolatedCVIndices.insert(2);
	  }

          if ((boundaryStatus & 2) != 0)
	 {
		patchControlVerticesArray[7] = (allSUbdivVertices[controlVertexIndices[6]] * 2) - 
                                                                    allSUbdivVertices[controlVertexIndices[5]];
		patchControlVerticesArray[11] = (allSUbdivVertices[controlVertexIndices[10]] * 2) - 
                                                                      allSUbdivVertices[controlVertexIndices[9]];

		extrapolatedCVIndices.insert(7);
		extrapolatedCVIndices.insert(11);
	}

        if ((boundaryStatus & 4) != 0)
	{
	       patchControlVerticesArray[13] = (allSUbdivVertices[controlVertexIndices[9]] * 2) - 
                                                                     allSUbdivVertices[controlVertexIndices[5]];
	       patchControlVerticesArray[14] = (allSUbdivVertices[controlVertexIndices[10]] * 2) - 
                                                                      allSUbdivVertices[controlVertexIndices[6]];

		extrapolatedCVIndices.insert(13);
		extrapolatedCVIndices.insert(14);
	}

        if ((boundaryStatus & 8) != 0)
	{
	        patchControlVerticesArray[4] = (allSUbdivVertices[controlVertexIndices[5]] * 2) - 
                                                                    allSUbdivVertices[controlVertexIndices[6]];
		patchControlVerticesArray[8] = (allSUbdivVertices[controlVertexIndices[9]] * 2) - 
                                                                    allSUbdivVertices[controlVertexIndices[10]];

		extrapolatedCVIndices.insert(4);
		extrapolatedCVIndices.insert(8);
	}

        //  Now safe to extrapolate corner points:
	if ((boundaryStatus & 1) != 0)
	{
		patchControlVerticesArray[0] = (allSUbdivVertices[controlVertexIndices[4]] * 2) - 
                                                                    allSUbdivVertices[controlVertexIndices[8]];
		patchControlVerticesArray[3] = (allSUbdivVertices[controlVertexIndices[7]] * 2) - 
                                                                    allSUbdivVertices[controlVertexIndices[11]];

		extrapolatedCVIndices.insert(0);
		extrapolatedCVIndices.insert(3);
	}

        if ((boundaryStatus & 2) != 0)
	{
		if(extrapolatedCVIndices.find(3) == extrapolatedCVIndices.end())
		   patchControlVerticesArray[3] = (allSUbdivVertices[controlVertexIndices[2]] * 2) - 
                                                                       allSUbdivVertices[controlVertexIndices[1]];

		patchControlVerticesArray[15] = (allSUbdivVertices[controlVertexIndices[14]] * 2) - 
                                                                      allSUbdivVertices[controlVertexIndices[13]];

		extrapolatedCVIndices.insert(3);
		extrapolatedCVIndices.insert(15);
	}

        if ((boundaryStatus & 4) != 0)
	{
		patchControlVerticesArray[12] = (allSUbdivVertices[controlVertexIndices[8]] * 2) - 
                                                                     allSUbdivVertices[controlVertexIndices[4]];

		if(extrapolatedCVIndices.find(15) == extrapolatedCVIndices.end())
		   patchControlVerticesArray[15] = (allSUbdivVertices[controlVertexIndices[11]] * 2) - 
                                                                         allSUbdivVertices[controlVertexIndices[7]];

		extrapolatedCVIndices.insert(12);
		extrapolatedCVIndices.insert(15);
	}

        if ((boundaryStatus & 8) != 0)
	{
	       if (extrapolatedCVIndices.find(0) == extrapolatedCVIndices.end())
		  patchControlVerticesArray[0] = (allSUbdivVertices[controlVertexIndices[1]] * 2) - 
                                                                      allSUbdivVertices[controlVertexIndices[2]];

	      if(extrapolatedCVIndices.find(12) == extrapolatedCVIndices.end())
		patchControlVerticesArray[12] = (allSUbdivVertices[controlVertexIndices[13]] * 2) - 
                                                                      allSUbdivVertices[controlVertexIndices[14]];

	     extrapolatedCVIndices.insert(0);
	     extrapolatedCVIndices.insert(12);
       }

       for (int cv = 0; cv < controlVertexIndices.size(); ++cv)
	{
		if (extrapolatedCVIndices.find(cv) != extrapolatedCVIndices.end())
		{
			patchControlVertices.push_back(patchControlVerticesArray[cv]);

			continue;
		}
		patchControlVertices.push_back(allSUbdivVertices[controlVertexIndices[cv]]);
	}

        //Create the patch b-spline surface...............
}

**Comment by jilliene** [comment]
Filed as internal issue #OSD-296

**Comment by barfowl** [comment]
Please go back and review the simple code that was originally provided.  That code correctly implements the extrapolation of "missing" boundary points for a fixed array of 16 control points with the appropriate subset of points populated and the boundary mask indicating the remaining points to be assigned.  The effectiveness of the extrapolation scheme (which is a standard technique for uniform B-splines) and the code that implements it is evident by its long-standing use in OpenSubdiv.

That code contains 16 lines that extrapolate up to 12 missing points.  Every extrapolated point P is trivially computed from two interior points A and B where P = A + (A - B) = 2*A - B.

The first 8 lines deal with the 8 "edge points" {1,2,4,7,8,11,13,14} and their extrapolation is unique.  All extrapolated edge points depend on the 4 most interior points {5,6,9,10}.

The second 8 lines deal with the 4 "corner points" which are extrapolated from two edge points.  Each pair of edge points is guaranteed to exist at this point -- either provided originally or just extrapolated above.  A corner point may also be extrapolated twice (with the same result, as can be shown algebraically) when two boundary bits are set -- which is the case causing you trouble.

Each boundary bit clearly affects 4 boundary points: 2 edge points in its first test and 2 corner points in its second.  There is no "degeneracy" for corner points.  A corner point -- correctly extrapolated once any of its boundary edges is detected -- does not "coincide" with one of the interior points (unless interior points happen to coincide).

The diagram you have constructed and the related comments do not accurately reflect the extrapolation scheme being applied.  And the modifications you have made to the original code no longer implements the intended scheme correctly.

I suggest revisiting the original code, understanding what it is doing, and then revisiting the modifications previously made to suit your needs so that it works correctly.

It also appears that the diagrams from the documentation have the sense of the boundary bits backwards, which may be an unfortunate distraction but the correspondence of bits to edges is obvious in the code provided.  The sense of the boundary bits has not changed in any version of OpenSubdiv to my knowledge, so I have no idea whether they have always been incorrect in those figures or if they accurately represented some early version.

(I have also renamed this issue to reflect the problem being experienced here rather than stating that a a particular feature -- the InfSharpPatch option in this case -- is not working as advertised, which will distract others interested in that feature.)

**Comment by VadiMysore** [comment]
Hi @barfowl - thanks for getting back to me. I did review the original code. May be I am missing something. The code that I posted in my previous post above was just an experimental one. I took out the "optimization" to not to extrapolate a corner point if it was already done. I checked and rechecked against the original logic you had supplied and I am not finding anything amiss. 

I will check again though.

**Comment by barfowl** [comment]
The original code deals with a fixed array of 16 control points.  A subset is provided, edge points may be extrapolated and those edge points then used as the pair of source points to extrapolate corner points.  Everything takes place in that fixed array of 16.

Your code separates the source points from those in the array of 16 that the given code was meant to deal with.  Your array of 16 is never populated with the subset of interior points that the original code expects.  Instead, you modify all extrapolation assignments to use source values taken from the "AllSubdivVertices" array.  But the edge points that are locally extrapolated and needed to derive the corner points -- and which do not exist in "AllSubdivVertices" -- are computed and stored in that array of 16.

The fact that you have split the points into separate source and destination locations is the source of your problem.

**Comment by VadiMysore** [comment]
@barfowl - Hi Barry! Thanks so much for spotting the error. I realized the issue after your response before the last one that I was not really storing the source points for a patch in the local control vertex array and I was using the original array of control vertices for the extrapolated corner control vertices instead of the extrapolated boundary edge control vertices.

The issue may be closed now.

Do you still think that OpenSubdiv itself should fill in the missing control vertices instead of each client having to do this separately? A method can be supported on the PatchTable in the least to compute the missing control vertices for a boundary patch.

**Comment by barfowl** [comment]
Yes, consideration has been given to how to make a method publicly available.  Since the PatchTable does not deal at all with these "extrapolated" or "missing" points, adding a method there may not be a good choice since it will add further confusion to the different kinds of "points" that the PatchTable already deals with.  A specific method for BSpline patches is more likely, but such low-level utilities for the different patch types do not exist in Far (though some exist in the hardware shading interfaces, where the code I provided exists).
