### ISSUE TITLE
Update documentation build scripts for Python 3

### ISSUE THREAD

**Issue by ldo** [PixarAnimationStudios/OpenSubdiv#1151]
Python 2 is mere months away from becoming a museum piece, so time to move on!

[ldo-python3-doc.patch.txt](https://github.com/PixarAnimationStudios/OpenSubdiv/files/3360667/ldo-python3-doc.patch.txt)

**Comment by jilliene** [comment]
Filed as internal issue #OSD-297

**Comment by c64kernal** [comment]
Thanks @ldo -- that's very helpful and I'm sure will benefit lots of users.  Please make sure you have a CLA signed with us, otherwise we can't accept any contributions.  More info here: http://graphics.pixar.com/opensubdiv/docs/contributing.html

Also, while it's true that Python 2 is on its way out very shortly, there are lots of users and studios that have not yet upgraded, so we will need to support both for the foreseeable future -- so if you're inclined to turn this into a PR, please make sure it works with Python 2 as well.

Thanks again, really appreciate it!

**Comment by david-geiger** [comment]
Hi,

It would be great if documentation can be ported to python3.

For now we have to disable build of documentation on Mageia Cauldron as we have dropped completely the python2 support.

Regards,
David

**Comment by davidgyu** [comment]
This has been fix by #1265 and #1266
