### ISSUE TITLE
Issue when building with VC141 in VS2019

### ISSUE THREAD

**Issue by oracle3001** [PixarAnimationStudios/OpenSubdiv#1161]
For a very long complicated reason, I have to use Cuda v10.0. The default toolset vc142 in VS2019 is not compatible with v10.0, therefore I am forced to use toolset vc141 (which is the compiler that comes with VS2017, but can also be installed into VS2019).

However, there is a strange error. Despite, settings up the whole solution with toolset vc141, there seems to be some strange mismatch in the Cmake file used when building osd_static_gpu.

```
1>Building NVCC (Device) object opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/Release/osd_static_gpu_generated_cudaKernel.cu.obj
1>cudaKernel.cu
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\yvals_core.h(378): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.22 or newer.
1>-ccbinC:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64
1>CMake Error at osd_static_gpu_generated_cudaKernel.cu.obj.Release.cmake:226 (message):
1>  Error generating
1> ...opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/Release/osd_static_gpu_generated_cudaKernel.cu.obj 
```

As you can see despite ccbin using 14.16 i.e toolset vc141, for some reason a header file in vc142 is being checked.

**Comment by davidgyu** [comment]
I haven't tried that configuration. But I can confirm that I am able to build successfully using VS2019 (Visual Studio Professional 2019 14.23.28105) and CUDA v10.1 Would you be able to use 10.1 instead of 10.0?

**Comment by oracle3001** [comment]
No, unfortunately I am using OpenSubdiv with tensorflow and that only supports Cuda v10.0, which in turn only supports VS2017.

**Comment by davidgyu** [comment]
In that case I would be tempted to build using the VS2017 toolchain. OpenSubdiv uses the CUDA support built into CMake, and we typically rely on the default Visual Studio toolchains: e.g.

  $ cmake -G "Visual Studio 15 2017 Win64" --system-information
CMAKE_CXX_COMPILER == "C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe"

- and -

  $ cmake -G "Visual Studio 16 2019" --system-information
CMAKE_CXX_COMPILER == "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe"

I suppose you could setup a custom toolchain to use vc141 with an otherwise vc142 system, but I have never tried to do that and don't have any particular guidance about how to get that to work.

**Comment by jilliene** [comment]
Filed as internal issue #OSD-304

**Comment by davidgyu** [comment]
Marking this closed. We've verified that OpenSubdiv builds well with VS2017 and VS2019 and CUDA 10.1 These kinds of build errors are typically arise from unsupported or incompatible versions of CUDA and VS which is beyond the scope of this project. Hopefully, you are up and running with recent versions of TensorFlow which should support CUDA 10.1
