### ISSUE TITLE
GLSL Shader Error when running glViewer Example

### ISSUE THREAD

**Issue by oracle3001** [PixarAnimationStudios/OpenSubdiv#1162]
I get the following stream of errors when running the glViewer example on a Windows 10 machine running a Nvidie GeForce 960M ( OpenGL 4.6, Nvidia Driver 436.48), with OSD built using VS2017.

OpenSubdiv Error: 4
    Error compiling GLSL shader: 0(1951) : error C1103: too few parameters in function call

**Comment by jilliene** [comment]
Filed as internal issue #OSD-305

**Comment by davidgyu** [comment]
Can you provide any more details about the conditions where you are seeing this error? Right after launching the app? Or after selecting specific options? We haven't seen this on newer (2080ti) or older (750M) cards running the latest Windows 10 and recent graphics drivers. Thanks!

**Comment by oracle3001** [comment]
It occurs as soon as the glViewer example launches, and then is a continuous stream of these errors.

**Comment by davidgyu** [comment]
Hmm. Definitely not seeing this here on our test systems. If you're hitting this on glViewer launch then the compile that is failing is from the drawing shader not one of the stencil evaluation shaders (since glViewer defaults to using CPU stencil evaluation).

The next step would be to capture the shader source that is being set on the shader that is failing to compile. That second number in the error string is a shader source line number, i.e. line 1951 in your initial message. If you can identify the specific shader code that is raising the error that would be super helpful. Thanks!

**Comment by davidgyu** [comment]
Marking this closed. We recently ran extensive tests of v3.4.0 and the current dev branch on a number of systems: Windows, macOS, Linux, AMD, Intel, NVIDIA and Visual Studio 2010 through 2019 and didn't encounter this problem.
