### ISSUE TITLE
Some questions about boundary interpolation schemes 

### ISSUE THREAD

**Issue by PixelClear** [PixarAnimationStudios/OpenSubdiv#1223]
Hello ,

I am trying to use OpenSubDiv and I have simple quad. This quad is made of two triangles.
I am using LOOP scheme as my quad is made of only triangles.
For boundary interpolation I am using VTX_BOUNDARY_EDGE_AND_CORNER.
So I am expecting after subdivision quad will not have smooth corners but I get following image 

![OpenSubDiv](https://user-images.githubusercontent.com/18286222/113744152-71b64000-96d2-11eb-93b8-5d6e85f533ab.png)

I am not sure why I am getting two corners smooth.
Can someone tell me what settings I am missing?

**Comment by barfowl** [comment]
Unfortunately the "interpolation" part of the "boundary interpolation" options is a little misleading...

With a triangulated quad, two of your vertices are considered corners (one incident face) and the other two at the ends of the diagonal are not (two incident faces).

When you use VTX_BOUNDARY_EDGE_AND_CORNER, the corner vertices are considered "sharp" and so the surface will actually interpolate the vertex.  But other vertices on boundaries are not treated the same way.  From the documentation for both VTX_BOUNDARY_EDGE_ONLY and VTX_BOUNDARY_EDGE_AND_CORNER:  "A sequence of boundary vertices defines a smooth curve to which the limit surface along boundary faces extends."  So any boundary vertex that is not a corner -- a boundary vertex with more than one incident face -- will be approximated by a smooth curve.

There is no boundary interpolation option that makes the boundary a piecewise linear curve connecting the boundary vertices.  In the absence of that, you can explicitly add sharpness values to all of the boundary vertices if that is the effect you want to achieve.

Otherwise -- considering examples other than a simple quad -- you may only want to sharpen the subset of boundary vertices that corresponded to corners that you wanted sharp in the mesh prior to triangulation.  Unfortunately, general polygonal triangulation (that is not aware of subdivision) has the potential to change subdivision behavior when new edges are added to corner vertices.

**Comment by PixelClear** [comment]
Thanks a lot for the detailed explanation. I will do as you suggested.
