### ISSUE TITLE
CMake configuration error on dev branch

### ISSUE THREAD

**Issue by nyue** [PixarAnimationStudios/OpenSubdiv#1263]
At the following latest commit I just pulled

```
commit 40eee124f42e412311ca8a1700072f276a9d96f3 (HEAD -> dev, origin/dev)
Merge: 514ddccd b5cbbdfc
Author: Barry Fowler <barfowl@gmail.com>
Date:   Fri Sep 9 18:37:40 2022 -0700

    Merge pull request #1262 from barfowl/bfr_evaluate_default
    
    Address failures in default execution of Bfr regression test
```

I am seeing these errors

```
CMake Error at CMakeLists.txt:715 (add_dependencies):
  The dependency target "DEPENDS" of target "public_headers" does not exist.
Call Stack (most recent call first):
  opensubdiv/sdc/CMakeLists.txt:65 (osd_add_doxy_headers)
```

**Comment by barfowl** [comment]
The commit cited was a minor change to the source code and should not have impacted any builds. It is the previous commit that is the issue:

```
commit 514ddccd1561f5f8de7bc3c35a298f784f3a0fcf
Merge: 698c7242 e627e482
Author: David G Yu <davidgyu@gmail.com>
Date:   Fri Sep 9 18:04:41 2022 -0700

    Merge pull request #1261 from davidgyu/dev_cmake_version
    
    Updated CMake minimum version to 3.12
```

I'm seeing the same error since updating my fork. The error is being triggered as part of Doxygen generation, so it can be avoided temporarily by not building the documentation (and that explains why the CI builds succeeded).

There are some other configuration changes currently on deck that may overlap with this (@davidgyu, is that the case?) so lets wait for those to settle before doing anything specific here.

**Comment by davidgyu** [comment]
Sorry about the breakage! As @barfowl mentioned we have a few more documentation related changes on the way that will fix this.

**Comment by nyue** [comment]
I have been able to build it now.

**Comment by davidgyu** [comment]
Thanks for confirming!
