### ISSUE TITLE
bfr: Handling of triangles and mix quads+triangle meshes ?

### ISSUE THREAD

**Issue by nyue** [PixarAnimationStudios/OpenSubdiv#1281]
Hi,

  I am trying to learn about the new bfr API

  I have been testing with making stencil evaluation with my own sets of UVs, I am using bfr_tutorial_1_5 as a starting point.

  Then I started trying out geometries I created.

```
# File exported by Houdini 19.5.303 (www.sidefx.com)
# 4 points
# 12 vertices
# 4 primitives
# Bounds: [-0.942810297, -0.333329707, -0.816497624] to [0.471405149, 1, 0.816497624]
g 
v 0 1 0
v -0.942810297 -0.333329707 0
v 0.471405149 -0.333329707 0.816497624
v 0.471405149 -0.333329707 -0.816497624
vt 0.722624719 0.419783443 0
vt 0.4655599 0 0
vt 0.979689538 0 0
vt 0.14841646 0.954223633 0
vt 0 0.534440219 0
vt 0.445249379 0.534440219 0
vt 0.762392759 0.859877348 0
vt 0.46555984 0.440093935 0
vt 0.910809159 0.440093935 0
vt 0 0.257064849 0
vt 0.445249379 0 0
vt 0.445249379 0.514129698 0
g 
f 1/1 3/2 4/3
f 1/4 4/5 2/6
f 1/7 2/8 3/9
f 2/10 4/11 3/12
```

  When I provided a tetra.obj, it seems that some of the limit evaluation via stencils for some of my UV position produces really large values

e.g.

```
[SNIP]
0.210669 0.056042 -0.105268
0.207616 0.041382 -0.120274
0.192808 -0.226078 -20366.437500
0.195310 0.011246 -0.122661
[SNIP]
0.214391 0.055420 -0.115940
0.201976 -0.157476 -17281.484375
0.203720 0.029377 -0.117777
0.194656 0.016549 -0.130847
-0.000255 0.031989 -0.230865
[SNIP]
```

  I wonder if that is related to [this](https://graphics.pixar.com/opensubdiv/docs/images/bfr_param_subfaces_abc_uv.png)

  Is it the responsibility of the caller to ensure that the input geometries are always quads before using bfr ?

Cheers

**Comment by barfowl** [comment]
To answer your last question first... No, it is not the caller's responsibility to ensure a mesh is always quads. One of Bfr's design goals was to make it easier to deal with non-quad faces.

I had a look and and don't find any issues evaluating UVs with this shape -- either directly or using stencils. I noticed that the UVs assigned are linear, so their evaluation avoids most of the internal complications dealing with triangles in a Catmull-Clark mesh.

Check to make sure you are creating and using the face-varying Surface for your UV evaluation and not the Surface used for position. The position Surface has 4 control points for the whole tet while the UV surface has only 3 for the linear UVs of a triangular face, so a 4th unexpected point involved in the UV evaluation may be at fault.

If that's not the issue, a better place to start might be tutorial_1_3 with face-varying UVs rather than tutorial_1_5. Changing the UV evaluation from the existing use of Evaluate() with patch points to EvaluateStencil() with control points (either direct from the mesh or gathered locally) would be less likely to mix up the position and UV Surfaces or associated data.

Regarding the diagram you noted of parametric discontinuities for triangles in a quad mesh...

This should not be an issue for any of the use cases illustrated in the tutorials. Any parametric coordinate pair that Bfr provides (via the Tessellation or Parameterization classes) can be used to compute an accurate result. Users must be wary of _computing their own parametric coordinate pairs_ by interpolating between those provided by Bfr -- that is where the presence of the illustrated parametric discontinuities can be a problem.

Hope that helps...

**Comment by nyue** [comment]
Thank you @barfowl for the suggestion on starting with tutorial_1_3

I have made this attempt https://github.com/nyue/OSDQuestions/blob/main/limit_stencil_with_fvar_uv/bfr_tutorial_1_3.cpp#L280

Using as much of the original code as possible and only creating the minimal necessary Control Points information required for EvaluateStencil

My printout of the data still shows fairly large values at some evaluated uv locations

**Comment by barfowl** [comment]
From the code you provide, you ignored the uv locations provided by the Tessellation and computed your own for the complete unit square (lines 307-315). These are what are used to evaluate a triangular face. So many of your uv locations are out of bounds for the expected parameterization (which consists of 3 quadrangulated sub-faces).

If you are going to determine uv locations yourself, you will have to deal with the different possible parameterizations (quad, triangle, n-sided) to match each face. Use of the Parameterization and Tessellation classes is intended to spare you as much of that as possible.

**Comment by barfowl** [comment]
As a follow-up to my previous comment, these two figures ([here](https://graphics.pixar.com/opensubdiv/docs/images/bfr_param_subfaces_3.png) and [here](https://graphics.pixar.com/opensubdiv/docs/images/bfr_param_subfaces_3_uv.png), from the Bfr documentation on [Parameterization](https://graphics.pixar.com/opensubdiv/docs/bfr_overview.html#bfr-navlink-parameterization)) illustrate how a triangle for Catmull-Clark subdivision is parameterized.

If you really need to determine your own parametric coordinates for these cases, you can deal with the parametric coordinates of the quad "sub-faces" instead and use methods provided by Bfr::Parameterization to convert them to coordinates of the face.

For instance, if you prefer to deal with cases using the same coordinates as Ptex, there are methods to convert coordinates between the face and "normalized sub-face coordinates" -- which are equivalent to Ptex. The interface to patches in Far forced users to deal with Ptex faces and coordinates in these cases, so this will be familiar to those who have done so.

**Comment by nyue** [comment]
The work flow I have in mind allows user to provide a set of UVs. That, I know; will be a requirement.

I will have to dive deeper into understanding Bfr::Parameterization to make meaningful progress. I am unsure if Ptex will assist/hinder my quest but I will have a look too. I suspect I have much to learn before I can embark on building my tool.

Thank you for the detailed explanation @barfowl 

Cheers

**Comment by nyue** [comment]
@barfowl I see my mistakes now and I believe I have everything I need to resume building my prototype idea.

The key is in your comment about quadrangulated sub-faces.

Since you have already mentioned TopologyRefiner, it is my error not to use that to find the UVs of the corner of the 3 points of the triangle face and **only** perform LimitStencil evaluation within the UV range that exists for each of the face [my error to simply generate a square as you noted]

Thank you once again for helping me think through more clearer to arrive at a way forward.

Kind regards

**Comment by davidgyu** [comment]
Filed as internal issue #OSD-395
