### ISSUE TITLE
Maximum value of refinement level ?

### ISSUE THREAD

**Issue by nyue** [PixarAnimationStudios/OpenSubdiv#393]
As a test, I increase the refinement level for a simple cube to see what is being generated and noticed that after level '3', the number of faces stays the same

I am debugging my code but I thought I'd ask if there is some refinement limit

Here is the print out of the statistic which triggered this question

numPtexFaces    = 6
numLevels       = 9
maxLevel        = 8
isUniform       = false
numFVarChannels = 1
Per channel information
	numFVarValuesTotal[channel=0] = 2532
Per level and per channel information
	numFaces[0] = 6
		numFVarValues[level=0][channel=0] = 24
	numFaces[1] = 24
		numFVarValues[level=1][channel=0] = 54
	numFaces[2] = 96
		numFVarValues[level=2][channel=0] = 150
	numFaces[3] = 216
		numFVarValues[level=3][channel=0] = 384
	numFaces[4] = 216
		numFVarValues[level=4][channel=0] = 384
	numFaces[5] = 216
		numFVarValues[level=5][channel=0] = 384
	numFaces[6] = 216
		numFVarValues[level=6][channel=0] = 384
	numFaces[7] = 216
		numFVarValues[level=7][channel=0] = 384
	numFaces[8] = 216
		numFVarValues[level=8][channel=0] = 384

**Comment by manuelk** [comment]
If you are using adaptive refinement, it is quite possible to reach a level where every feature has been isolated and no further faces are being generated (ex : a torus does not isolate a single face). 

For all practical intents and purposes, the code assumes level 10 to be the maximum level (hence 10 being the highest crease sharpness)

**Comment by nyue** [comment]
Is there some way to check (either directly or from inference) if the requested refinement level no longer makes sense ?

**Comment by barfowl** [comment]
The adaptive refinement applied here is continuing to produce the same
number of faces (216) at each additional level, it does not stop generating
faces.  This is typical of adaptive refinement as each extra-ordinary
feature is more closely approximated -- in this case the 216 faces arise
from 27 faces around each of the 8 valence-3 vertices of the cube.

No additional levels will be generated if they do not improve the
refinement.  How many levels "makes sense" depends on what you want to do.

- barry

**Comment by manuelk** [comment]
Sorry - missed the fact that your geometry was a cube : Barry is correct. Every level of isolation adds the same number of faces as the previous one because extraordinary vertices will keep generating the same number of sub-patches indefinitely. 

Currently, it is up to client-code to make the decision as to which level is appropriate. Ideally, you want the minimum level to correspond at least to the value of the sharpest crease in the mesh so that the limit surface is correct, but you may not want to generate too many patches and cut off extraordinary vertex isolation before level 10 (for most practical applications, 6 should be enough)

**Comment by jcowles** [comment]
It seems like adaptive refinement is working as expected (per barfowl's comment), closing.
