### ISSUE TITLE
VS Errors with GL stuff..

### ISSUE THREAD

**Issue by MidnightCow2016** [PixarAnimationStudios/OpenSubdiv#736]
Hi,

I managed to get OpenSubdiv working in my plugin and running successfully in the host application, however, after swapping from CPU run code over to the GL related functions, i'm getting this error in VS 2010:

```
1>c:\program files\microsoft sdks\windows\v7.1\include\gl\gl.h(1499): error C2143: syntax error : missing ')' before 'constant'
1>c:\program files\microsoft sdks\windows\v7.1\include\gl\gl.h(1499): error C2143: syntax error : missing ';' before 'constant'
1>c:\program files\microsoft sdks\windows\v7.1\include\gl\gl.h(1499): error C2059: syntax error : ')'
```

It's probably something obvious, but i haven't been able to nail it down.  Google brings up a number of similar problems and usually it's related to using opengl and putting includes in the wrong order etc..

My includes look like this minus the host application api stuff:

```
#include <windows.h>
#include <vector>

//Host Application API Includes

#include "MyPlugin.h"

#include <opensubdiv/osd/glComputeEvaluator.h>
#include <opensubdiv/osd/glVertexBuffer.h>
#include <opensubdiv/osd/glMesh.h>

#include <opensubdiv/far/topologyDescriptor.h>
#include <opensubdiv/far/stencilTable.h>
#include <opensubdiv/far/stencilTableFactory.h>
```

Any ideas or suggestions are welcome.  Not sure if something in OpenSubdiv is causing the conflict or if it's the host application API itself, there wasn't any issues obviously until adding the osd/gl stuff..

**Comment by c64kernal** [comment]
Hmmm... a file containing only this:

```
#include <windows.h>
#include <vector>

#include <osd/glComputeEvaluator.h>
#include <osd/glVertexBuffer.h>
#include <osd/glMesh.h>

#include <far/topologyDescriptor.h>
#include <far/stencilTable.h>
#include <far/stencilTableFactory.h>
```

and a stub main() seems to compile okay.  Would that compile for you?

**Comment by davidguk2015** [comment]
Hi there,

Thanks for the reply.  Yeah i think i'll strip back and test without dependencies on the host applications API..  Other thoughts were possibly the VS project properties themselves.  It's compiling as a 64 bit plugin.  The only reason i added windows.h was because i had a similar small group of errors related to windows\v7.1\include\msxml.h which adding that fixed.

Thanks again and will report back once i've tested further.  It's never something obvious is it :)

**Comment by davidguk2015** [comment]
Stripping back and removing all references to the host applications API worked..  It turns out there is a define of 'pi' in the host applications api headers which is also used in the windows sdk.  The specific line in gl.h that was flagged was this:

    typedef void (APIENTRY * PFNGLARRAYELEMENTARRAYEXTPROC)(GLenum mode, GLsizei count, const GLvoid* pi);

I'm assuming as it was used as a 'const' in gl.h it caused problems..  And so if i add the following undef after the host api includes ( and before the OSD includes ) it compiles fine:

    #undef pi

Thanks again i know this wasn't strictly an issue with the OpenSubdiv api!

**Comment by davidguk2015** [comment]
Ah, actually not quite..

It compiles ok as above without any active code..  But just testing with:

    static Osd::EvaluatorCacheT<Osd::GLComputeEvaluator> glComputeEvaluatorCache;

Causes the build to throw:

    1>MyPlugin.obj : error LNK2001: unresolved external symbol "public: __cdecl OpenSubdiv::v3_0_2::Osd::GLComputeEvaluator::~GLComputeEvaluator(void)" (??1GLComputeEvaluator@Osd@v3_0_2@OpenSubdiv@@QEAA@XZ)

And so when i then remove the undef again, it's back to having the gl.h errors from the original post :/

**Comment by c64kernal** [comment]
Depending on how you built the OpenSubdiv libraries, that symbol should be provided when you link against osdGPU.lib.

**Comment by davidguk2015** [comment]
I actually added far_obj/sdc_obj/vtr_obj as references as i couldn't get the lib to link properly..  Maybe i should try again.

Date: Sat, 29 Aug 2015 22:58:10 -0700

**Comment by davidguk2015** [comment]
Still the same problem when just linking osdGPU.lib and osdCPU.lib as additional dependencies in the VisualStudio project..

All i have to do is include anything GL related from osd.  I'm linking to the release build of the libs.  Not sure if there's a setting somewhere in the project properties of my project or if i should be compiling OSD differently to get this working..

Apologies again as i know this is not strictly an issue with OSD itself.

**Comment by c64kernal** [comment]
You could try statically linking against osd_obj as you were doing far_obj/sdc_obj/vtr_obj before, but unfortunately I'm not sure why dynamically linking osdGPU.lib isn't working in your configuration.

**Comment by davidgyu** [comment]
We believe this has been address as part of PR #917 (static CRT on Windows) or tracked as part of #71 (DLL build on Windows) Thanks!
