### ISSUE TITLE
Adaptive subdivision not rendering on older Mac/AMD hardware

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/OpenSubdiv#770]
This is a long standing issue, new bug 23992994 filed with Apple

**Comment by jcowles** [comment]
To give a few more details: on my 2011 MacBook Pro which has a pre-GCN AMD GPU, adaptive tessellation is not rendering correctly, it explodes like this:

![image](https://cloud.githubusercontent.com/assets/1510114/11969097/c73f8ace-a8c9-11e5-9c65-c0dee194bac2.png)

**Comment by manuelk** [comment]
Adaptive sort-of worked on my 2010 MBP, except for Gregory patches being bugged in an interesting way (they "lagged" a few frames behind when moving the camera...)

What's your compute API ?

**Comment by jtran56** [comment]
Filed as internal issue #151665.

**Comment by davidgyu** [comment]
Hey Jeremy!

Fun and quick project for self-isolation weekend was to dig up my oldest Mac w/ tessellation to see how things look with OpenSubdiv 3.4.0

The oldest machine in my personal testing gauntlet is a Mid 2010 Mac Pro tower with an ATI Radeon HD 5770, pre-GCN TeraScale 2 (VLIW5)  "Evergreen" GPU .  The most recent supported OS for this is macOS 10.13.6 High Sierra. So, I loaded that and Xcode 10.1 onto a spare SSD and was up and running with OpenSubdiv.

Looking pretty good! Here are two screen shots with screen-space adaptive, fractional tessellation w/ and w/o smooth UV interpolation using the GPU XFB compute path.

![macOS-10 13 6-AMD-5770](https://user-images.githubusercontent.com/1672753/77267794-f7e71c00-6c60-11ea-86bf-2d0093f08ad3.png)
![macOS-10 13 6-AMD-5770-FVAR](https://user-images.githubusercontent.com/1672753/77267805-03d2de00-6c61-11ea-9b0e-41b28ee94c39.png)

Somewhat astonishingly, I have inherited a similarly ancient All-in-one Windows PC with an AMD E1-1500 (Llano) APU (also TeraScale2 graphics) and was able to setup and run Windows 10 1909 w/ Visual Studio 2019 and achieve similar results.

On both platforms, I noticed some problems with single-crease-patch evaluation, but all of this hardware is end-of-life from Apple and AMD, and we've been running well for awhile now with NVIDIA (since Fermi) and AMD GCN and RDNA GPUs.
