### ISSUE TITLE
Derivative with respect to control points

### ISSUE THREAD

**Issue by Kalkasas** [PixarAnimationStudios/OpenSubdiv#911]
With Limit Stencils it is possible to get the partial derivatives of an arbitrary point on the surface with respect to (s,t) coordinates. 
Is it also possible to get the partial derivatives with respect to the control points?

**Comment by amooty** [comment]
Filed as internal issue #140951.

**Comment by barfowl** [comment]
If I understand what you are looking for, it is already available to you -- but perhaps not in the way you may expect...

Usually the limit surface S is considered a function S(s,t) with the control points Pi as constant coefficients of basis functions for each, i.e. Bi(s,t)).  If you want to consider the Pi variables and differentiate S wrt them, since S is a linear combination of Pi and their corresponding Bi(s,t), the derivative wrt some Pi is simply its corresponding basis function Bi(s,t).

The set of pairs used in the evaluation of S(s,t) -- a control point identifier and its basis function evaluated at (s,t) -- is what defines each LimitStencil, represented as an <index, weight> pair.  So given a LimitStencil for the position evaluated at some (s,t), the derivative wrt to some control point Pj is just the weight corresponding to Pj, i.e. the weight whose index matches Pj (or 0 if the control point Pj is not present in the stencil).

Since these "derivatives" are constant wrt the control points, there is no need to repeatedly evaluate them when control point values change.  Once the StencilTable is constructed, the required values are stored as part of the LimitStencils and are available for inspection.

Personally I don't think of these values as "partial derivatives wrt control points" since they are just the basis functions B(s,t), or the coefficients used in the evaluations, which have other purposes.  While you can think of them as partial derivatives wrt the control points, there is only one such derivative since the limit surface functions are linear in terms of the control points and so all higher order derivatives wrt them are 0.

I make this point in the event that functionality in the existing API is lacking and needs future work -- there is potentially more value in framing that functionality in terms of the basis functions than derivatives wrt control points.  It's a bit ironic that the values desired from such differentiation are actually the fundamental building blocks of the simplest evaluation.  Even the most basic evaluation involves evaluating an entire set of Bi(s,t), so lower level functionality to compute individual Bi(s,t) for a single control point is not currently available.

**Comment by Kalkasas** [comment]
That solved my issues. Thank you for your detailed explanation.
